export const FINANCE_ACTIONS = {
  SET_TRANSACTIONS: 'SET_TRANSACTIONS',
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  SET_SAVINGS: 'SET_SAVINGS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  ADD_CATEGORY: 'ADD_CATEGORY',
  SET_BALANCE: 'SET_BALANCE',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
}
